# Generated by Django 5.1.6 on 2025-02-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionitem",
            name="ends_at",
        ),
        migrations.AddField(
            model_name="auctionitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Fashion", "Fashion"),
                    ("Home", "Home Goods"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auctionitem",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
