# Generated by Django 5.1.6 on 2025-02-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0002_remove_auctionitem_ends_at_auctionitem_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("Electronics", "Electronics"),
                    ("Fashion", "Fashion"),
                    ("Home Goods", "Home Goods"),
                ],
                max_length=50,
            ),
        ),
    ]
