# Generated by Django 5.1.6 on 2025-04-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auctionitem_end_time_auctionitem_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
